package com.app.model.enums;

public enum Interests {
	ANIME,CARTOON,CARS,BIKE,DOGS,CATS,SONGS,READING,TRAVELLING,DRAWING,SINGING,ARTS,GAMES,ARVR,TECHNOLOGY,CODING,TV,SPORTS,PHOTOGRAPHY,ACTING,HARDWARE
}
